language: node_js

node_js:
  - "node"
  - "lts/*"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn prettier-diff
  - yarn test-ci
